### PR TITLE
#8 bring back skipping tests

### LINKED ISSUE #8: Fix 3 skipped test cases
At the moment, there are 3 skipped test cases (which were not skipped before splitting)
We need to fix them or remove them

### PR DESCRIPTION
**Pull request by tuanlc**
- #8 bring back skipping tests cases
- #8 fix unit test

Resolve #8

### CODE REVIEW

**Comment by huy-ta** [comment]
The CI is not running for this repo?

**Comment by huy-ta** [comment]
> The CI is not running for this repo?

It is missing in the list of CI jobs: https://github.com/OpenPaaS-Suite/CI-jobs/blob/main/CreateJobs.groovy

**Comment by tuanlc** [comment]
@huy-ta Added CI and pipeline passed

**Review by piavgh — COMMENTED** [review]
Did you figure out why the compile component returns view on mobile screen but not on desktop?

**Review by MichaelBailly — APPROVED** [review]

**Comment by tuanlc** [comment]
> Did you figure out why the compile component returns view on mobile screen but not on desktop?

Not yet. Took hours to debug but cannot figure out why?

**Review by piavgh — APPROVED** [review]

**Pull request merged**
